#!/bin/bash

echo "╔══════════════════════════════════════════════════════════════════╗"
echo "║                                                                  ║"
echo "║     ✅ CONTRACTS DEPLOYED - ADDRESSES UPDATED!                  ║"
echo "║                                                                  ║"
echo "╚══════════════════════════════════════════════════════════════════╝"
echo ""
echo "📋 Your deployed contract addresses:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "PredictionMarket: 0x5fbdb2315678afecb367f032d93f642f64180aa3"
echo "AIOracle:         0xe7f1725e7734ce288f8367e1bb143e90bb3f0512"
echo "GaslessRelayer:   0x9fe46736679d2d9a65f0992f2272de9f3c7fa6e0"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ Updated files:"
echo "  • src/lib/contracts/addresses.ts (Chain ID 31337)"
echo "  • .env.local (NEXT_PUBLIC_*_ADDRESS)"
echo ""
echo "🚀 Next steps:"
echo ""
echo "1️⃣  Start the dev server:"
echo "   npm run dev"
echo ""
echo "2️⃣  Configure MetaMask:"
echo "   • Network: Localhost 8545"
echo "   • RPC URL: http://127.0.0.1:8545"
echo "   • Chain ID: 31337"
echo "   • Import Account:"
echo "     0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
echo ""
echo "3️⃣  Open browser:"
echo "   http://localhost:3000"
echo ""
echo "4️⃣  Test predictions:"
echo "   • Connect wallet"
echo "   • Create a market"
echo "   • Place predictions (YES/NO)"
echo "   • Test resolution"
echo "   • Claim winnings!"
echo ""
echo "🔍 Verify contracts on local blockchain:"
echo "   • Your Hardhat node is running in the background"
echo "   • All transactions will show in the Hardhat terminal"
echo ""
echo "✅ You're all set! Start the dev server now!"
